### ISSUE TITLE
How to change the buffer of any nvim-dap-ui window temporarily?

### ISSUE THREAD

**Issue by nyngwang** [rcarriga/nvim-dap-ui#212]
As title. I'm a plugin author and I want to change the buffer of any `nvim-dap-ui` window temporarily.

- If I call `:bn` then the buffer of the window on enter will be changed to the next buffer. But instead, I want to change the buffer of the current `nvim-dap-ui` split.
- I assume that you have used some options to prevent changing the buffer of any window of `nvim-dap-ui`, but I cannot confirm this myself.

Thanks.

**Comment by nyngwang** [comment]
Found #58 and ae3b003

**Comment by nyngwang** [comment]
I found another problem with deleting the `DapuiWindowsSetup` augroup: if I press `o` on the `dapui_stacks` split, the buffer of the window on enter will not be changed. Instead, the buffer of the current split will be changed. This is unwanted behavior for me...

**Comment by rcarriga** [comment]
I've added a `force_buffers` option to the setup which can disable this behaviour :smile:

**Comment by nyngwang** [comment]
@rcarriga Hi, thanks for your help with b2fdea8, it's working very well. But I encountered another problem(should I open another issue?):

- If I trigger the `open` function of `dapui_stacks`, then I expect the buffer of the main window(i.e. where I called `dapui.open()`) to be changed.
- But in the demo, it's the buffer of the split being changed.

https://user-images.githubusercontent.com/24765272/215243819-b0c31300-b1d3-4750-8305-9a993462e564.mov

**Comment by rcarriga** [comment]
I've added a window picker so users can choose which window to open a frame in

**Comment by nyngwang** [comment]
I just encountered a little trouble when trying e400a44: My cursor stuck at a strange place after I typed the letter and pressed `<CR>` to confirm my selection.

(Unfortunately, I don't know how to provide a minimal config for this. So I instead provide my config of NeoZoom.lua below)

```lua
{
  'nyngwang/NeoZoom.lua',
  config = function ()
    require('neo-zoom').setup()
    vim.keymap.set('n', '<CR>', function () vim.cmd('NeoZoomToggle') end, { silent = true, nowait = true })
  end
}
```

Here is the DEMO:

https://user-images.githubusercontent.com/24765272/217331140-20db6062-8725-4533-8794-c4b96611ddf2.mov

**Comment by rcarriga** [comment]
It looks like you're pressing shift+B in that video which wouldn't work. I've added a change to convert upper case to lower case characters to avoid that issue. The window changed after you pressed escape because of a separate bug which should now be fixed also :smile:

**Comment by nyngwang** [comment]
Sorry for my bad news: I got this error (where the window handle `1020` is indeed the main window where I started debugging) after confirming my choice.

```
   Error  04:10:10 msg_show.emsg E5108: Error executing lua: ...ng/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/util.lua:149: Failed to switch to window 1020
stack traceback:
	[C]: in function 'nvim_set_current_win'
	...ng/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/util.lua:149: in function 'set_win_pos'
	...ng/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/util.lua:164: in function <...ng/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/util.lua:144>
	...cal/share/nvim/lazy/nvim-dap-ui/lua/dapui/client/lib.lua:48: in function 'callback'
	.../share/nvim/lazy/nvim-dap-ui/lua/dapui/render/canvas.lua:146: in function <.../share/nvim/lazy/nvim-dap-ui/lua/dapui/render/canvas.lua:138>
```

**Comment by rcarriga** [comment]
I'm afraid I can't reproduce, I'll need specific instructions on how to do so

**Comment by nyngwang** [comment]
@rcarriga Here are the steps: (apologies for my forgetfulness)

1. With the same config in my [comment](https://github.com/rcarriga/nvim-dap-ui/issues/212#issuecomment-1421242385) above.
2. Remember the result of `:lua print(vim.api.nvim_get_current_win())` for the main window where the debugging start.
3. Press `<Enter>` (or call `:NeoZoomToggle`) on the `dapui_stacks` split.
4. Call `:lua vim.api.nvim_set_current_win(winid)` where `winid` is the value at setup 2.

**Comment by nyngwang** [comment]
Basically, #239 fixes most of the bug, because I see there is no harm just ignore the error. But there is still the same issue as I have stated [above](https://github.com/rcarriga/nvim-dap-ui/issues/212#issuecomment-1421242385). Here is the demo of the current status:


https://user-images.githubusercontent.com/24765272/218745061-1f5dbfa3-2444-49be-a1c7-7464cae58802.mov

**Comment by rcarriga** [comment]
I can't reproduce the issue where no selection hints are shown. It's likely something setting your statusline which is how nvim-dap-ui sets the hints https://github.com/rcarriga/nvim-dap-ui/blob/9adb362a74f452f3f65c1e4e076f5e18c3a3e773/lua/dapui/util.lua#L115-L124

**Comment by nyngwang** [comment]
@rcarriga In fact, I didn't get the point of window selection, as I will always select B in my use case. Is it possible to opt out of the feature? Anyway, thanks for your trying to reproduce.

**Comment by rcarriga** [comment]
The window selector is not specifically for this case, it is so users can select which window to replace in general. I've added a `select_window` config option to allow overriding it.

**Comment by nyngwang** [comment]
Closing as bdb94e3 has helped me a lot. I did encounter some more related issues with that evil `dap-repl` buffer, but I believe it can be resolved in a new thread.
